### ISSUE TITLE
Figure out dependencies between variables

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/pyBabyMaker#7]
Currently:

```yml
    rename:
        mu_isMuon: mu_is_mu
        mu_PIDmu: mu_pid_mu
    calculation:
        # Temp variables
        mu_pid: "^Bool_t; MU_PID(mu_is_mu, mu_pid_mu)"  # <--- this won't work, as mu_is_mu is not defined when mu_pid is defined
```

I'd like have some automatic dependency resolver to define variables in the right order.
